AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvPrefix:
    Type: String
  ContainerDefinitionsImage:
    Type: String

Resources:
  SampleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${EnvPrefix}-SampleTaskDefinitionFamily
      RetentionInDays: 14

  SampleExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvPrefix}-SampleECSExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  SampleTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: SampleTaskDefinitionFamily
      ExecutionRoleArn: !GetAtt SampleExecutionRole.Arn
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: !Sub ${EnvPrefix}-SampleContainer
          Image: !Ref ContainerDefinitionsImage
          Essential: true
          PortMappings:
            - HostPort: 80
              ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref SampleLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          MemoryReservation: 128
          Secrets:
            - Name: DB_HOST
              ValueFrom: /SAMPLE/DB_HOST
            - Name: DB_NAME
              ValueFrom: /SAMPLE/DB_NAME
            - Name: DB_USERNAME
              ValueFrom: /SAMPLE/DB_USERNAME
            - Name: DB_PASSWORD
              ValueFrom: /SAMPLE/DB_PASSWORD

Outputs:
  SampleTaskDefinition:
    Value: !Ref SampleTaskDefinition