AWSTemplateFormatVersion: '2010-09-09'
Description: Restore Aurora MySQL Cluster and Instance from Cluster Snapshot

Parameters:
  DBClusterIdentifier:
    Description: Identifier for the restored Aurora MySQL cluster
    Type: String
  DBClusterSnapshotIdentifier:
    Description: Identifier of the Aurora MySQL cluster snapshot to restore from
    Type: String
  DBInstanceIdentifier:
    Description: Identifier for the restored Aurora MySQL instance
    Type: String
  DBInstanceClass:
    Description: Instance class for the restored Aurora MySQL instance
    Type: String
  DBSubnetGroupName:
    Description: Name of the DB subnet group
    Type: String
  VpcSecurityGroupIds:
    Description: List of Security Group IDs for the database cluster and instance
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref DBClusterIdentifier
      SnapshotIdentifier: !Ref DBClusterSnapshotIdentifier
      EngineMode: provisioned
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VpcSecurityGroupIds: !Ref VpcSecurityGroupIds
      Tags:
        - Key: Name
          Value: !Ref DBClusterIdentifier

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroupName
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier

Outputs:
  AuroraClusterEndpoint:
    Description: The endpoint URL of the restored Aurora MySQL cluster
    Value: !GetAtt AuroraDBCluster.Endpoint.Address
  AuroraClusterPort:
    Description: The port of the restored Aurora MySQL cluster
    Value: !GetAtt AuroraDBCluster.Endpoint.Port
  AuroraInstanceEndpoint:
    Description: The endpoint URL of the restored Aurora MySQL instance
    Value: !GetAtt AuroraDBInstance.Endpoint.Address
  AuroraInstancePort:
    Description: The port of the restored Aurora MySQL instance
    Value: !GetAtt AuroraDBInstance.Endpoint.Port