AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvPrefix:
    Type: String
  CodeBuildServiceRole:
    Type: String


Resources:
  CodeBuildLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub ${EnvPrefix}-sample-bg-cicd-code-build

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${EnvPrefix}-sample-code-build
      Environment:
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      ServiceRole: !Ref CodeBuildServiceRole
      LogsConfig: 
        CloudWatchLogs:
          Status: "ENABLED"
          GroupName: !Ref CodeBuildLogGroup
      Visibility: "PRIVATE"

Outputs:
  CodeBuildProject:
    Value: !Ref CodeBuildProject