AWSTemplateFormatVersion: '2010-09-09'
Description: Restore Aurora MySQL Cluster and Instance from Cluster Snapshot

Parameters:
  EnvPrefix:
    Type: String
  DBClusterIdentifier:
    Type: String
  DBClusterSnapshotIdentifier:
    Type: String
  DBInstanceIdentifier:
    Type: String
  DBInstanceClass:
    Type: String
  DBSubnetGroupName:
    Type: String
  VpcSecurityGroupIds:
    Type: CommaDelimitedList

Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      DBClusterIdentifier: !Sub ${EnvPrefix}-${DBClusterIdentifier}
      SnapshotIdentifier: !Ref DBClusterSnapshotIdentifier
      EngineMode: provisioned
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VpcSecurityGroupIds: !Ref VpcSecurityGroupIds

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      DBInstanceIdentifier: !Sub ${EnvPrefix}-${DBInstanceIdentifier}
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroupName

Outputs:
  AuoraEndpoint:
    Value: !GetAtt AuroraDBCluster.Endpoint.Address